### ISSUE TITLE
Output Formatting

### ISSUE THREAD

**Issue by Armandotrsg** [Neuvax/IntegratedAct1#4]
# Output Formatting

## Description
The program needs to format and display the output as specified in the problem statement. The output consists of three parts:
1. Part 1: (true | false) if the file `transmission1.txt` contains the code (sequence of chars) contained in the file `mcode1.txt`, and so on for each combination of transmission and mcode files.
2. Part 2: `startPosition endPosition` (for `transmission1.txt` file) and `startPosition endPosition` (for `transmission2.txt` file) for the longest "mirrored" code (palindrome) found in each file.
3. Part 3: `startPosition endPosition` (for longest common substring between stream files).

## Requirements
- Develop a function or a set of functions to format and display the output as specified in the problem statement.
- The function(s) should take the results from the malicious code detection, palindrome detection, and longest common substring detection and format them appropriately.

## Acceptance Criteria
- The function(s) should successfully format and display the output as specified in the problem statement.
- The output should be clear and easy to understand.

## Suggested Implementation
- Use the standard C++ I/O functions to display the output.
- Format the output as specified in the problem statement.

**Comment by Neuvax** [comment]
Done
